### ISSUE TITLE
Macros related to lists appear to have no effect

### ISSUE THREAD

**Issue by groenroos** [alleyinteractive/wp-block-converter#31]
### Description of the bug

When trying to apply a macro to the list elements in my HTML, they seem to have no effect in the final HTML:

```php
Block_Converter::macro( 'ol', function ( \DOMNode $node ) {
	/* Convert to paragraph just to see if it works */
	return new Block( 'core/paragraph', [], $node->textContent );
} );
```

```html
<!-- wp:heading {"level":2} --><h2>Test content</h2><!-- /wp:heading -->

<!-- wp:list {"ordered":true} --><ol>
<li>
<p>Foo</p>
</li>
<li>
<p>Bar</p>
</li>
</ol><!-- /wp:list -->
```

The same happens regardless of whether the macro is targeting `"ol"`, `"li"`, or `"ul"`.

However, the exact same macro targeting `"h2"` does work:

```php
Block_Converter::macro( 'h2', function ( \DOMNode $node ) {
	/* Convert to paragraph just to see if it works */
	return new Block( 'core/paragraph', [], $node->textContent );
} );
```

```html
<!-- wp:paragraph -->Test content<!-- /wp:paragraph -->

<!-- wp:list {"ordered":true} --><ol>
<li>
<p>Foo</p>
</li>
<li>
<p>Bar</p>
</li>
</ol><!-- /wp:list -->
```

### Steps To Reproduce

1. Use the test HTML below
2. Write a macro attempting to affect the conversion of `<ol>` and/or `<li>` tags
3. `$converter = new Block_Converter( $html ); return $converter->convert();`
4. The resulting HTML will look identical to when no macro is present - i.e. the macro wasn't applied

### Additional Information

Test HTML:

```php
$html = "<h2>Test content</h2>\n<ol>\n<li>\n<p>Foo</p>\n</li>\n<li>\n<p>Bar</p>\n</li>\n</ol>\n";
```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the Block_Converter class to properly apply macros for 'ul', 'ol', and 'li' elements. Updated the __call method to handle these elements separately and apply macros if defined.

You can review changes in this commit: https://github.com/mnmnk43434/alleyinteractive-wp-block-converter-31/commit/d418b4ec568190372f55c8a7353dd9d0a9af3552.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
