### ISSUE TITLE
Some block conversion issues identified

### ISSUE THREAD

**Issue by guzmandrade-dev** [alleyinteractive/wp-block-converter#8]
### Description

First, thank you for this library, it's an awesome idea. 

Working with it, I identified some minor issues dealing with images:

- Function `upload_image` should return an URL, but instead is returning an attachment ID
- `remove_image_args` has issues when the image URLs have formats such as `//domain.../image`, `http://localhost:8888`, which can be an issue when working with some CDNs or local development environments, for example.
- The converter method `img` might fail, and the return would be `WP_Error`, and maybe a try-catch would be useful.
- the Block constructor requires `block_name` to be of type `string` but the WordPress Core function `get_comment_delimited_block_content` can receive `null` as `block_name`, where the block content would be returned.

### Use Case

As mentioned, the source images might have URLs with format `//domain.../image`, `http://localhost:8888/.../image` but `remove_image_args` would fail.

If the Blocks constructor accepted `block_name` as null, it would be possible to return a group of blocks directly, for example to return the blocks from a registered pattern.

**Comment by dlh01** [comment]
Hey @guzmandrade-wds — thanks for submitting this report and the PR!

@scottnelle, one of these observations sounds like what you reported in https://github.com/alleyinteractive/feed-consumer/issues/50:

> Function upload_image should return an URL, but instead is returning an attachment ID

Do you think you'd be able to review or test the PR to confirm?

**Comment by guzmandrade-dev** [comment]
Thank you for your prompt reply. Please let me know if you have any questions.

**Comment by kevinfodness** [comment]
For visibility, I'm looking at this today also.

**Comment by kevinfodness** [comment]
@guzmandrade-wds @scottnelle @dlh01 I pushed some changes to the PR to address my code review feedback. All of the automated tests are passing, but we should kick the tires on this as well. Can you all help to do that, please?

**Comment by dlh01** [comment]
I don't have a real-world example to hand to test with, but I left a couple comments after reading the PR. In general, the changes make sense to me!
